name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn ci
      run: yarn --frozen-lockfile
    - name: lint
      run: yarn run lint
    - name: test:jest
      run: yarn run test
    - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./
          browser: chrome
          build: yarn build
          start: yarn preview
          wait-on: "http://localhost:3000"
    - name: typescript
      run: yarn run type-check
    - name: build
      run: yarn run build
    
