name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn ci
      run: yarn --frozen-lockfile
    - name: lint
      run: yarn run lint
    - name: test:jest
      run: yarn run test
    - name: typescript
      run: yarn run type-check
    - name: build
      run: yarn run build
    - name: test:cypress
      uses: cypress-io/github-action@v4.2.0
      with:
        install: false
        start: yarn run preview
        wait-on-timeout: 300
        browser: chrome
      env:
        VITE_VERCEL_GOOGLE_CLIENT_ID: ${{ secrets.VITE_VERCEL_GOOGLE_CLIENT_ID }}
        VITE_VERCEL_GOOGLE_SCOPE: ${{ secrets.VITE_VERCEL_GOOGLE_SCOPE }}
        VITE_VERCEL_GOOGLE_DISCOVERY_DOCS: ${{ secrets.VITE_VERCEL_GOOGLE_DISCOVERY_DOCS }}
        VITE_VERCEL_GOOGLE_API_KEY: ${{ secrets.VITE_VERCEL_GOOGLE_API_KEY }}

        VITE_VERCEL_OPENWEATHERMAP: ${{ secrets.VITE_VERCEL_OPENWEATHERMAP }}
        VITE_VERCEL_OPENWEATHERMAP_LOCATIONS: ${{ secrets.VITE_VERCEL_OPENWEATHERMAP_LOCATIONS }}
        VITE_VERCEL_OPENWEATHERMAP_API_KEY: ${{ secrets.VITE_VERCEL_OPENWEATHERMAP_API_KEY }}

        VITE_VERCEL_METEOSOURCE: ${{ secrets.VITE_VERCEL_METEOSOURCE }}
        VITE_VERCEL_METEOSOURCE_API_KEY: ${{ secrets.VITE_VERCEL_METEOSOURCE_API_KEY }}

        VITE_VERCEL_GEOAPIFY: ${{ secrets.VITE_VERCEL_GEOAPIFY }}
        VITE_VERCEL_GEOAPIFY_API_KEY: ${{ secrets.VITE_VERCEL_GEOAPIFY_API_KEY }}
